### ISSUE TITLE
Resource Upload Image

### ISSUE THREAD

**Issue by thanujamsc** [chathuras/TSD-SRRS#18]
http://localhost/resource/create

Fire Fox 52

Priority - Low
Severity - Low

1. Load and log in as admin.
2. Go to Resource management -> Resources section.

Better to facilitate a image upload to increase usability
![my](https://cloud.githubusercontent.com/assets/24395781/22852312/49a04bb0-f05f-11e6-88ac-1774c6e543cf.png)
.

Pls find the attached.

**Comment by chinthaka78** [comment]
Feature provided
