### ISSUE TITLE
Manual ADD

### ISSUE THREAD

**Issue by thanujamsc** [chathuras/TSD-SRRS#23]
https://srrs-reports.herokuapp.com/passedReservations

V 1.0

FF 52

Sprint V 3

1. Load the above URL.

2. Instead of manual time enter better to give a date picker to the user.

Pls find the attached.

![my](https://cloud.githubusercontent.com/assets/24395781/22852389/28def7a8-f061-11e6-9d11-e813a40b7b0a.png)

**Comment by amilarajans** [comment]
fixed
