### ISSUE TITLE
2 times no data show.

### ISSUE THREAD

**Issue by thanujamsc** [chathuras/TSD-SRRS#28]
http://localhost/reservation/categories

Fire Fox 52

Sprint V 03

Priority - Normal
Severity - Normal

1. Log in as admin and go to reports.
2. In past reservation section show 2 no records test.

Pls find the attached.

![my](https://cloud.githubusercontent.com/assets/24395781/22857974/1b5b07a4-f0d7-11e6-98a6-e2838f59c78e.png)

**Comment by amilarajans** [comment]
fixed the issue

**Comment by thanujamsc** [comment]
fixed.
